    
# Copyright (C) 2020 The uOFW team
# See the file COPYING for copying permission.

TARGET = libparse_http
OBJS = libparse_http.o

#DEBUG = 1

LIBS = -lKernel_Library -lThreadManForUser

include ../../lib/build.mak
