language: cpp

branches:
  only:
    - master

env:
  global:
    - secure: "aiH0ZGvhmY7ldfRxngIZHDuWE7ZF5UpVL577hIOUW1P+t+5lOq4hXpTaJgbaEgl0ZQ9GudeFpwx+OvUoxGwLa1wofGGSygeYRl0rfui3XkNx+5RevZ+KOuRQcv+4gJ15twvhP4+XHKfE/B8HWTO5IGN+ntRn+NzXJQLUZFXnOW8=" # GH_AUTH

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove mingw* -q

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

install:
  - cd ..
  - git clone https://github.com/pspdev/psptoolchain
  - cd psptoolchain
  - sudo apt-get install g++ build-essential autoconf automake cmake doxygen bison flex libncurses5-dev libsdl1.2-dev libreadline-dev libusb-dev texinfo libgmp3-dev libmpfr-dev libelf-dev libmpc-dev libfreetype6-dev zlib1g-dev libtool libtool-bin subversion git tcl unzip wget
  - sudo ./toolchain-sudo.sh
  - export PSPDEV=/usr/local/pspdev
  - export PATH=$PATH:$PSPDEV/bin
  - cd $TRAVIS_BUILD_DIR

script:
  - make -k

after_script:
  - |
    if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then
      mkdir gh-pages && cd gh-pages
      git clone "https://github.com/$TRAVIS_REPO_SLUG.git" --branch gh-pages .
      export GIT_ROOT=$TRAVIS_BUILD_DIR

      if [[ $(git -C $GIT_ROOT log --pretty=%s -1 $TRAVIS_COMMIT) != *"[docs-skip]"* ]]; then
        doxygen ../docs/Doxyfile
      fi

      if [[ $(git -C $GIT_ROOT log --pretty=%s -1 $TRAVIS_COMMIT) == *"[exec-build]"* || $(git -C $GIT_ROOT diff-tree --name-only --no-commit-id $TRAVIS_COMMIT $GIT_ROOT/utils) ]]; then
        cd $GIT_ROOT/utils
        mkdir -p ../gh-pages/executables

        make mrproper all CC=gcc -m32 CXX=g++ -m32
        for file in $(find */ -executable -type f); do
          mv $file "../gh-pages/executables/$(basename $file)-i386"
        done

        make mrproper all CC="i686-w64-mingw32-gcc -m32" CXX="i686-w64-mingw32-g++ -m32"
        for file in $(find */ -executable -type f); do
          mv $file "../gh-pages/executables/$(basename $file)-i386.exe"
        done
      fi

      cd $GIT_ROOT/gh-pages

      git config user.email "travis@example.com"
      git config user.name "uOFW Doc builder"

      git remote set-url origin "https://${GH_AUTH}@github.com/$TRAVIS_REPO_SLUG.git"
      git checkout gh-pages
      git add .
      git commit -am "Rebuilt docs for $TRAVIS_COMMIT"

      git push origin gh-pages 2>&1 | sed "s/${GH_AUTH}/[secure]/gi"
    fi

