# Copyright (C) 2020 The uOFW team
# See the file COPYING for copying permission.

TARGET = chkreg
OBJS = chkreg.o

#DEBUG = 1

LIBS = -lThreadManForKernel -lsceIdStorage_driver -lpspsemaphore

include ../../lib/build.mak
